import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const page = () => {

  return (
    <div>About</div>
  )
}

export default page